//------------
//System Values
//------------
var STAGE_WIDTH = 600,
	STAGE_HEIGHT = 600,
	TIME_PER_FRAME = 200,

	GAME_FONTS = "bold 20px sans-serif";



var PATH_CHAR = "ziggy.png";
var PATH_BACKGROUND="Road.png";
var PATH_CAR="car.png";



var CHAR_WIDTH = 40,
	CHAR_HEIGHT = 40,
	CHAR_START_X = 520,
	CHAR_START_Y = 10,
	IMAGE_START_X = 0,
	IMAGE_START_Y = 0,
	SPRITE_WIDTH = 120;


	var BALL1_WIDTH = 48,
		BALL1_HEIGHT = 48,
		BALL1_START_X = 500,
		BALL1_START_Y = 0,
		BALL1_START_X = 0,
		BALL1_START_Y = 0,
		SPRITE_WIDTH = 192;

		var BALL2_WIDTH = 48,
			BALL2_HEIGHT = 48,
			BALL2_START_X = 500,
			BALL2_START_Y = 0,
			BALL2_START_X = 0,
			BALL2_START_Y = 0,
			SPRITE_WIDTH = 192;

			var BALL3_WIDTH = 48,
				BALL3_HEIGHT = 48,
				BALL3_START_X = 500,
				BALL3_START_Y = 0,
				BALL3_START_X = 0,
				BALL3_START_Y = 0,
				SPRITE_WIDTH = 192;

				var BALL4_WIDTH = 48,
					BALL4_HEIGHT = 48,
					BALL4_START_X = 500,
					BALL4_START_Y = 0,
					BALL4_START_X = 0,
					BALL4_START_Y = 0,
					SPRITE_WIDTH = 192;

					var BALL5_WIDTH = 48,
						BALL5_HEIGHT = 48,
						BALL5_START_X = 500,
						BALL5_START_Y = 0,
						BALL5_START_X = 0,
						BALL5_START_Y = 0,
						SPRITE_WIDTH = 192;

						var BALL6_WIDTH = 48,
							BALL6_HEIGHT = 48,
							BALL6_START_X = 500,
							BALL6_START_Y = 0,
							BALL6_START_X = 0,
							BALL6_START_Y = 0,
							SPRITE_WIDTH = 192;

var TEXT_PRELOADING = "Loading ...",
	TEXT_PRELOADING_X = 200,
	TEXT_PRELOADING_Y = 200;
